In [1]:
import pandas as pd
import numpy as np
import matplotlib as mt
import glob as glob

In [2]:
filenames = glob.glob('Combined_*[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p]*160c.dta')
list_of_all_dfs  = [pd.read_stata(f) for f in filenames]
list_of_all_dfs = [list_of_all_dfs[i].set_index('xwaveid') for i in range(16)]

In [3]:
prev = [list_of_all_dfs[i].filter(regex='jbhrcpr$') for i in range(16)]
sex = [list_of_all_dfs[i].filter(regex='hgsex$') for i in range(16)]
job = [list_of_all_dfs[i].filter(regex='esbrd$') for i in range(16)]
status = [list_of_all_dfs[i].filter(regex='esdtl$') for i in range(16)]

#make them into DataFrames
job = [pd.DataFrame(job[i]) for i in range(16)]
sex = [pd.DataFrame(sex[i]) for i in range(16)]
prev = [pd.DataFrame(prev[i]) for i in range(16)]
status = [pd.DataFrame(status[i]) for i in range(16)]

result1 = [pd.merge(prev[i], status[i], left_index=True, right_index=True) for i in range(16)]
result1 = [pd.merge(result1[i], sex[i], left_index=True, right_index=True) for i in range(16)]

#getting results for just full-time employed
pt = [result1[i][result1[i].iloc[:, -2] == '[2] Employed PT'] for i in range(16)]

In [4]:
# cutting down to females
ptf = [pt[i][pt[i].iloc[:, -1] == '[2] Female'] for i in range(16)]

#looking at just the jbhrcpr variable 
ptf1 = [ptf[i].filter(regex='jbhrcpr$') for i in range(16)]

#getting a count for every variable
ptf1 = [pd.DataFrame(ptf1[i].iloc[:,0].value_counts()) for i in range(16)]

#getting total number of observations
ftotal = [ptf1[i].sum() for i in range(16)]
ftotal = [pd.DataFrame(ftotal[i]) for i in range(16)]
ftotal = [ftotal[i].T for i in range(16)]

# working out percentages
percent = [pd.DataFrame(ptf[i].iloc[:,0].value_counts(normalize=True))*100 for i in range(16)]
percent = [round(percent[i], 1) for i in range(16)]

#dropping unwanted responses
percent2 = [percent[i].drop(['[-1] Not asked', '[-1] Not asked', '[-10] Non-responding person', '[2] About the same', '[-3] Dont know', '[-4] Refused/Not stated'], errors='ignore') for i in range(16)]

percent2 = [percent2[i].reindex(index = ['[1] Fewer hours', '[3] More hours']) for i in range(16)]

#adding total into table
final = [pd.concat([ftotal[i], percent2[i]]) for i in range(16)]

# doing a manual merge for now :/
merge0 = pd.merge(final[0], final[1], left_index=True, right_index=True)
merge1 = pd.merge(merge0, final[2],left_index=True, right_index=True)
merge2 = pd.merge(merge1, final[3],left_index=True, right_index=True)
merge3 = pd.merge(merge2, final[4],left_index=True, right_index=True)
merge4 = pd.merge(merge3, final[5],left_index=True, right_index=True)
merge5 = pd.merge(merge4, final[6],left_index=True, right_index=True)
merge6 = pd.merge(merge5, final[7],left_index=True, right_index=True)
merge7 = pd.merge(merge6, final[8],left_index=True, right_index=True)
merge8 = pd.merge(merge7, final[9],left_index=True, right_index=True)
merge9 = pd.merge(merge8, final[10],left_index=True, right_index=True)
merge10 = pd.merge(merge9, final[11],left_index=True, right_index=True)
merge11 = pd.merge(merge10, final[12],left_index=True, right_index=True)
merge12 = pd.merge(merge11, final[13],left_index=True, right_index=True)
merge13 = pd.merge(merge12, final[14],left_index=True, right_index=True)
merge14 = pd.merge(merge13, final[15],left_index=True, right_index=True)


# creating 'All' column
all_ff = merge14.iloc[0,:].sum()
all_less = merge14.iloc[1,:].mean()
all_more = merge14.iloc[2,:].mean()
allf = pd.DataFrame([all_ff, all_less, all_more])
allf = round(allf, 1)
allf.index = merge14.index

merge14 = pd.merge(merge14, allf ,left_index=True, right_index=True)


# transposing so that its facing the right way
final_mergef = merge14.T

#adding names to columns
final_mergef.columns = ['All employed (number of observations)','Prefer to work less (%)', 'Prefer to work more (%)']

In [7]:
# doing it for males
# cutting down to females
ptm = [pt[i][pt[i].iloc[:, -1] == '[1] Male'] for i in range(16)]

#looking at just the jbhrcpr variable 
ptm1 = [ptm[i].filter(regex='jbhrcpr$') for i in range(16)]

#getting a count for every variable
ptm1 = [pd.DataFrame(ptm1[i].iloc[:,0].value_counts()) for i in range(16)]

#getting total number of observations
mtotal = [ptm1[i].sum() for i in range(16)]
mtotal = [pd.DataFrame(mtotal[i]) for i in range(16)]
mtotal = [mtotal[i].T for i in range(16)]

# working out percentages
mpercent = [pd.DataFrame(ptm[i].iloc[:,0].value_counts(normalize=True))*100 for i in range(16)]
mpercent = [round(mpercent[i], 1) for i in range(16)]

#dropping unwanted responses
mpercent2 = [mpercent[i].drop(['[-1] Not asked', '[-1] Not asked', '[-10] Non-responding person', '[2] About the same', '[-3] Dont know', '[-4] Refused/Not stated'], errors='ignore') for i in range(16)]
mpercent2 = [mpercent2[i].reindex(index = ['[1] Fewer hours', '[3] More hours']) for i in range(16)]

#adding total into table
finalm = [pd.concat([mtotal[i], mpercent2[i]]) for i in range(16)]


# doing a manual merge for now :/
mmerge0 = pd.merge(finalm[0], finalm[1], left_index=True, right_index=True)
mmerge1 = pd.merge(mmerge0, finalm[2],left_index=True, right_index=True)
mmerge2 = pd.merge(mmerge1, finalm[3],left_index=True, right_index=True)
mmerge3 = pd.merge(mmerge2, finalm[4],left_index=True, right_index=True)
mmerge4 = pd.merge(mmerge3, finalm[5],left_index=True, right_index=True)
mmerge5 = pd.merge(mmerge4, finalm[6],left_index=True, right_index=True)
mmerge6 = pd.merge(mmerge5, finalm[7],left_index=True, right_index=True)
mmerge7 = pd.merge(mmerge6, finalm[8],left_index=True, right_index=True)
mmerge8 = pd.merge(mmerge7, finalm[9],left_index=True, right_index=True)
mmerge9 = pd.merge(mmerge8, finalm[10],left_index=True, right_index=True)
mmerge10 = pd.merge(mmerge9, finalm[11],left_index=True, right_index=True)
mmerge11 = pd.merge(mmerge10, finalm[12],left_index=True, right_index=True)
mmerge12 = pd.merge(mmerge11, finalm[13],left_index=True, right_index=True)
mmerge13 = pd.merge(mmerge12, finalm[14],left_index=True, right_index=True)
mmerge14 = pd.merge(mmerge13, finalm[15],left_index=True, right_index=True)

# creating 'All' column
all_mm = mmerge14.iloc[0,:].sum()
all_less = mmerge14.iloc[1,:].mean()
all_more = mmerge14.iloc[2,:].mean()
allm = pd.DataFrame([all_mm, all_less, all_more])
allm = round(allm, 1)
allm.index = merge14.index

mmerge14 = pd.merge(mmerge14, allm ,left_index=True, right_index=True)

# transposing so that its facing the right way
final_mergem = mmerge14.T

#adding names to columns
final_mergem.columns = ['All employed (number of observations)', 'Prefer to work less (%)', 'Prefer to work more (%)']

In [10]:
final_table3 = pd.concat([final_mergem, final_mergef], axis=1)

In [11]:
final_table3.index = [ '2001 (1)', '2002 (2)', '2003 (3)', '2004 (4)', '2005 (5)', '2006 (6)', '2007 (7)', '2008 (8)', '2009 (9)', '2010 (10)', '2011 (11)', '2012 (12)', '2013 (13)', '2014 (14)', '2015 (15)', '2016 (16)', 'All']
final_table3

,All employed (number of observations),Prefer to work less (%),Prefer to work more (%),All employed (number of observations),Prefer to work less (%),Prefer to work more (%)
2001 (1),752.0,6.1,43.0,1975.0,9.8,29.5
2002 (2),750.0,4.9,44.3,1890.0,8.4,30.4
2003 (3),723.0,5.4,44.0,1871.0,9.1,31.5
2004 (4),714.0,5.7,39.1,1831.0,8.7,29.1
2005 (5),717.0,4.5,38.6,1973.0,9.1,29.7
2006 (6),774.0,6.1,39.8,1949.0,9.6,27.0
2007 (7),743.0,5.4,35.9,1930.0,9.2,28.8
2008 (8),702.0,5.7,34.2,1940.0,9.2,26.4
2009 (9),798.0,5.5,41.4,1961.0,7.8,28.1
2010 (10),778.0,5.9,38.3,2013.0,8.0,29.2
2011 (11),1055.0,5.4,40.3,2644.0,8.1,30.7
2012 (12),1036.0,5.3,40.0,2590.0,8.6,28.4
2013 (13),1100.0,3.6,42.6,2578.0,7.8,28.7
2014 (14),1104.0,4.4,43.9,2665.0,8.2,31.7
2015 (15),1103.0,4.4,42.3,2673.0,7.7,30.4
2016 (16),1129.0,3.6,42.0,2607.0,7.4,30.7
All,13978.0,5.1,40.6,35090.0,8.5,29.4