In [1]:
import pandas as pd
import numpy as np
import matplotlib as mt
import glob as glob

In [2]:
filenames = glob.glob('Combined_*[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p]*160c.dta')
list_of_all_dfs  = [pd.read_stata(f) for f in filenames]
list_of_all_dfs = [list_of_all_dfs[i].set_index('xwaveid') for i in range(16)]

In [3]:
prev = [list_of_all_dfs[i].filter(regex='jbhrcpr$') for i in range(16)]
sex = [list_of_all_dfs[i].filter(regex='hgsex$') for i in range(16)]
job = [list_of_all_dfs[i].filter(regex='esbrd$') for i in range(16)]
status = [list_of_all_dfs[i].filter(regex='esdtl$') for i in range(16)]

#make them into DataFrames
job = [pd.DataFrame(job[i]) for i in range(16)]
sex = [pd.DataFrame(sex[i]) for i in range(16)]
prev = [pd.DataFrame(prev[i]) for i in range(16)]
status = [pd.DataFrame(status[i]) for i in range(16)]

In [4]:
# looking to cut down to just full time employed Australians
result1 = [pd.merge(prev[i], status[i], left_index=True, right_index=True) for i in range(16)]
result1 = [pd.merge(result1[i], sex[i], left_index=True, right_index=True) for i in range(16)]


#getting results for just full-time employed
ft = [result1[i][result1[i].iloc[:, -2] == '[1] Employed FT'] for i in range(16)]

#again narrowing to full time females.
ftf = [ft[i][ft[i].iloc[:, -1] == '[2] Female'] for i in range(16)]

#looking at just the jbhrcpr variable 
ftf1 = [ftf[i].filter(regex='jbhrcpr$') for i in range(16)]


#getting a count for every variable
ftf1 = [pd.DataFrame(ftf1[i].iloc[:,0].value_counts()) for i in range(16)]

#getting total number of observations
total = [ftf1[i].sum() for i in range(16)]
total = [pd.DataFrame(total[i]) for i in range(16)]
total = [total[i].T for i in range(16)]

# working out percentages
percent = [pd.DataFrame(ftf[i].iloc[:,0].value_counts(normalize=True))*100 for i in range(16)]
percent = [round(percent[i], 1) for i in range(16)]

#dropping unwanted responses
percent2 = [percent[i].drop(['[-1] Not asked', '[-1] Not asked', '[-10] Non-responding person', '[2] About the same', '[-3] Dont know', '[-4] Refused/Not stated'], errors='ignore') for i in range(16)]


#adding total into table
final = [pd.concat([total[i], percent2[i]]) for i in range(16)]

In [5]:
# doing a manual merge for now :/
merge0 = pd.merge(final[0], final[1], left_index=True, right_index=True)
merge1 = pd.merge(merge0, final[2],left_index=True, right_index=True)
merge2 = pd.merge(merge1, final[3],left_index=True, right_index=True)
merge3 = pd.merge(merge2, final[4],left_index=True, right_index=True)
merge4 = pd.merge(merge3, final[5],left_index=True, right_index=True)
merge5 = pd.merge(merge4, final[6],left_index=True, right_index=True)
merge6 = pd.merge(merge5, final[7],left_index=True, right_index=True)
merge7 = pd.merge(merge6, final[8],left_index=True, right_index=True)
merge8 = pd.merge(merge7, final[9],left_index=True, right_index=True)
merge9 = pd.merge(merge8, final[10],left_index=True, right_index=True)
merge10 = pd.merge(merge9, final[11],left_index=True, right_index=True)
merge11 = pd.merge(merge10, final[12],left_index=True, right_index=True)
merge12 = pd.merge(merge11, final[13],left_index=True, right_index=True)
merge13 = pd.merge(merge12, final[14],left_index=True, right_index=True)
merge14 = pd.merge(merge13, final[15],left_index=True, right_index=True)


# creating 'All' column
all_ff = merge14.iloc[0,:].sum()
all_less = merge14.iloc[1,:].mean()
all_more = merge14.iloc[2,:].mean()
allf = pd.DataFrame([all_ff, all_less, all_more])
allf = round(allf, 1)
allf.index = merge14.index

merge14 = pd.merge(merge14, allf ,left_index=True, right_index=True)

In [6]:
# transposing so that its facing the right way
final_mergef = merge14.T

#adding names to columns
final_mergef.columns = ['All employed (number of observations)','Prefer to work less (%)', 'Prefer to work more (%)']

In [9]:
#again narrowing to full time males 
ftm = [ft[i][ft[i].iloc[:, -1] == '[1] Male'] for i in range(16)]

#looking at just the jbhrcpr variable 
ftm1 = [ftm[i].filter(regex='jbhrcpr$') for i in range(16)]

#getting a count for every variable
ftm1 = [pd.DataFrame(ftm1[i].iloc[:,0].value_counts()) for i in range(16)]

#getting total number of observations
total = [ftm1[i].sum() for i in range(16)]
total = [pd.DataFrame(total[i]) for i in range(16)]
total = [total[i].T for i in range(16)]

# working out percentages
percent = [pd.DataFrame(ftm[i].iloc[:,0].value_counts(normalize=True))*100 for i in range(16)]
percent = [round(percent[i], 1) for i in range(16)]

#dropping unwanted responses
percent2 = [percent[i].drop(['[-1] Not asked', '[-1] Not asked', '[-10] Non-responding person', '[2] About the same', '[-3] Dont know', '[-4] Refused/Not stated'], errors='ignore') for i in range(16)]
#adding total into table
final = [pd.concat([total[i], percent2[i]]) for i in range(16)]

#doing a manual merge for now :/
merge0 = pd.merge(final[0], final[1], left_index=True, right_index=True)
merge1 = pd.merge(merge0, final[2],left_index=True, right_index=True)
merge2 = pd.merge(merge1, final[3],left_index=True, right_index=True)
merge3 = pd.merge(merge2, final[4],left_index=True, right_index=True)
merge4 = pd.merge(merge3, final[5],left_index=True, right_index=True)
merge5 = pd.merge(merge4, final[6],left_index=True, right_index=True)
merge6 = pd.merge(merge5, final[7],left_index=True, right_index=True)
merge7 = pd.merge(merge6, final[8],left_index=True, right_index=True)
merge8 = pd.merge(merge7, final[9],left_index=True, right_index=True)
merge9 = pd.merge(merge8, final[10],left_index=True, right_index=True)
merge10 = pd.merge(merge9, final[11],left_index=True, right_index=True)
merge11 = pd.merge(merge10, final[12],left_index=True, right_index=True)
merge12 = pd.merge(merge11, final[13],left_index=True, right_index=True)
merge13 = pd.merge(merge12, final[14],left_index=True, right_index=True)
merge14 = pd.merge(merge13, final[15],left_index=True, right_index=True)

#gettting all column, adding to merge
all_m = merge14.iloc[0,:].sum()
all_less = merge14.iloc[1,:].mean()
all_more = merge14.iloc[2,:].mean()
allm = pd.DataFrame([all_m, all_less, all_more])
allm = round(allm, 1)
allm.index = merge14.index
merge14 = pd.merge(merge14, allm, left_index=True, right_index=True)

# transposing so that its facing the right way
final_mergem = merge14.T

#adding names to columns
final_mergem.columns = ['All employed (number of observations)','Prefer to work less (%)', 'Prefer to work more (%)']

In [11]:
final_table2 = pd.concat([final_mergem, final_mergef], axis=1)

final_table2.index = [ '2001 (1)', '2002 (2)', '2003 (3)', '2004 (4)', '2005 (5)', '2006 (6)', '2007 (7)', '2008 (8)', '2009 (9)', '2010 (10)', '2011 (11)', '2012 (12)', '2013 (13)', '2014 (14)', '2015 (15)', '2016 (16)', 'All']

final_table2

,All employed (number of observations),Prefer to work less (%),Prefer to work more (%),All employed (number of observations),Prefer to work less (%),Prefer to work more (%)
2001 (1),3797.0,34.9,9.7,2001.0,43.3,5.1
2002 (2),3575.0,36.8,9.0,1873.0,41.0,4.8
2003 (3),3524.0,36.6,7.5,1873.0,41.3,3.2
2004 (4),3441.0,36.1,7.9,1836.0,43.1,3.6
2005 (5),3587.0,34.7,8.1,1970.0,43.5,4.2
2006 (6),3579.0,34.6,7.3,2055.0,41.8,4.2
2007 (7),3565.0,33.5,7.0,2104.0,42.7,3.0
2008 (8),3635.0,32.0,8.0,2092.0,40.0,3.5
2009 (9),3686.0,32.1,8.1,2104.0,38.9,4.1
2010 (10),3731.0,29.7,8.7,2128.0,40.3,4.9
2011 (11),4794.0,30.4,9.3,2716.0,39.7,3.9
2012 (12),4664.0,29.3,8.9,2688.0,38.2,5.0
2013 (13),4555.0,28.5,8.9,2681.0,38.3,4.6
2014 (14),4566.0,28.3,9.2,2616.0,37.8,4.8
2015 (15),4568.0,29.0,8.3,2673.0,38.2,4.0
2016 (16),4547.0,28.5,8.3,2734.0,36.8,4.3
All,63814.0,32.2,8.4,36144.0,40.3,4.2