In [18]:
import pandas as pd
import numpy as np
import matplotlib as mt
import glob as glob
import matplotlib.pyplot as plt

In [2]:
filenames = glob.glob('Combined_*[a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p]*160c.dta')
list_of_all_dfs  = [pd.read_stata(f) for f in filenames]
list_of_all_dfs = [list_of_all_dfs[i].set_index('xwaveid') for i in range(16)]

In [3]:
#getting variables of interest
prev = [list_of_all_dfs[i].filter(regex='jbhrcpr$') for i in range(16)]
sex = [list_of_all_dfs[i].filter(regex='hgsex$') for i in range(16)]
job = [list_of_all_dfs[i].filter(regex='esbrd$') for i in range(16)]

#turning into dataframes
job = [pd.DataFrame(job[i]) for i in range(16)]
sex = [pd.DataFrame(sex[i]) for i in range(16)]
prev = [pd.DataFrame(prev[i]) for i in range(16)]

#merged into a single df 
result1 = [pd.merge(prev[i], job[i], left_index=True, right_index=True) for i in range(16)]
result1 = [pd.merge(result1[i], sex[i], left_index=True, right_index=True) for i in range(16)]

In [4]:
#getting results for just females, employed
female = [result1[i][result1[i].iloc[:, -1] == '[2] Female'] for i in range(16)]
female = [female[i][female[i].iloc[:, -2] == '[1] Employed'] for i in range(16)]
female1 = [female[i].filter(regex='jbhrcpr$') for i in range(16)]
female2 = [pd.DataFrame(female[i].iloc[:,0].value_counts()) for i in range(16)]

In [5]:
# getting total number of observations
total = [female2[i].sum() for i in range(16)]
total = [pd.DataFrame(total[i]) for i in range(16)]
total = [total[i].T for i in range(16)]

# looking to work out percentages
percent = [pd.DataFrame(female[i].iloc[:,0].value_counts(normalize=True))*100 for i in range(16)]
percent = [round(percent[i], 1) for i in range(16)]

#dropping unwanted responses
percent2 = [percent[i].drop(['[-1] Not asked', '[-1] Not asked', '[-10] Non-responding person', '[2] About the same', '[-3] Dont know', '[-4] Refused/Not stated'], errors='ignore') for i in range(16)]

#adding total into table
final = [pd.concat([total[i], percent2[i]]) for i in range(16)]

In [7]:
# doing a manual merge for now :/
merge0 = pd.merge(final[0], final[1], left_index=True, right_index=True)
merge1 = pd.merge(merge0, final[2],left_index=True, right_index=True)
merge2 = pd.merge(merge1, final[3],left_index=True, right_index=True)
merge3 = pd.merge(merge2, final[4],left_index=True, right_index=True)
merge4 = pd.merge(merge3, final[5],left_index=True, right_index=True)
merge5 = pd.merge(merge4, final[6],left_index=True, right_index=True)
merge6 = pd.merge(merge5, final[7],left_index=True, right_index=True)
merge7 = pd.merge(merge6, final[8],left_index=True, right_index=True)
merge8 = pd.merge(merge7, final[9],left_index=True, right_index=True)
merge9 = pd.merge(merge8, final[10],left_index=True, right_index=True)
merge10 = pd.merge(merge9, final[11],left_index=True, right_index=True)
merge11 = pd.merge(merge10, final[12],left_index=True, right_index=True)
merge12 = pd.merge(merge11, final[13],left_index=True, right_index=True)
merge13 = pd.merge(merge12, final[14],left_index=True, right_index=True)
merge14 = pd.merge(merge13, final[15],left_index=True, right_index=True)


# creating 'All' column
all_ff = merge14.iloc[0,:].sum()
all_less = merge14.iloc[1,:].mean()
all_more = merge14.iloc[2,:].mean()
allf = pd.DataFrame([all_ff, all_less, all_more])
allf = round(allf, 1)
allf.index = merge14.index

merge14 = pd.merge(merge14, allf ,left_index=True, right_index=True)

In [8]:
# transposing so that its facing the right way
final_mergef = merge14.T

#adding names to columns
final_mergef.columns = ['All employed (number of observations)','Prefer to work less (%)', 'Prefer to work more (%)']

In [10]:
#Part 2
#getting results for just males, employed
male = [result1[i][result1[i].iloc[:, -1] == '[1] Male'] for i in range(16)]
male = [male[i][male[i].iloc[:, -2] == '[1] Employed'] for i in range(16)]

male1 = [male[i].filter(regex='jbhrcpr$') for i in range(16)]
male2 = [pd.DataFrame(male[i].iloc[:,0].value_counts()) for i in range(16)]

# getting total number of observations
totalm = [male2[i].sum() for i in range(16)]
totalm = [pd.DataFrame(totalm[i]) for i in range(16)]
totalm = [totalm[i].T for i in range(16)]
bigtotalm= totalm

# looking to work out percentages
percentm = [pd.DataFrame(male[i].iloc[:,0].value_counts(normalize=True))*100 for i in range(16)]
percentm = [round(percentm[i], 1) for i in range(16)]


#dropping unwanted responses
percentm2 = [percentm[i].drop(['[-1] Not asked', '[-1] Not asked', '[-10] Non-responding person', '[2] About the same', '[-3] Dont know', '[-4] Refused/Not stated'], errors='ignore') for i in range(16)]


#adding total into table
finalm = [pd.concat([totalm[i], percentm2[i]]) for i in range(16)]


# doing a manual merge for now :/
mmerge0 = pd.merge(finalm[0], finalm[1], left_index=True, right_index=True)
mmerge1 = pd.merge(mmerge0, finalm[2],left_index=True, right_index=True)
mmerge2 = pd.merge(mmerge1, finalm[3],left_index=True, right_index=True)
mmerge3 = pd.merge(mmerge2, finalm[4],left_index=True, right_index=True)
mmerge4 = pd.merge(mmerge3, finalm[5],left_index=True, right_index=True)
mmerge5 = pd.merge(mmerge4, finalm[6],left_index=True, right_index=True)
mmerge6 = pd.merge(mmerge5, finalm[7],left_index=True, right_index=True)
mmerge7 = pd.merge(mmerge6, finalm[8],left_index=True, right_index=True)
mmerge8 = pd.merge(mmerge7, finalm[9],left_index=True, right_index=True)
mmerge9 = pd.merge(mmerge8, finalm[10],left_index=True, right_index=True)
mmerge10 = pd.merge(mmerge9, finalm[11],left_index=True, right_index=True)
mmerge11 = pd.merge(mmerge10, finalm[12],left_index=True, right_index=True)
mmerge12 = pd.merge(mmerge11, finalm[13],left_index=True, right_index=True)
mmerge13 = pd.merge(mmerge12, finalm[14],left_index=True, right_index=True)
mmerge14 = pd.merge(mmerge13, finalm[15],left_index=True, right_index=True)


#gettting all column, adding to merge
all_m = mmerge14.iloc[0,:].sum()
all_less = mmerge14.iloc[1,:].mean()
all_more = mmerge14.iloc[2,:].mean()
allm = pd.DataFrame([all_m, all_less, all_more])
allm = round(allm, 1)
allm.index = mmerge14.index
mmerge14 = pd.merge(mmerge14, allm, left_index=True, right_index=True)


# transposing so that its facing the right way
final_mergem = mmerge14.T

#adding names to columns
final_mergem.columns = ['All employed (number of observations)','Prefer to work less (%)', 'Prefer to work more (%)']

In [11]:
final_table1 = pd.concat([final_mergem, final_mergef], axis=1)

final_table1.index = [ '2001 (1)', '2002 (2)', '2003 (3)', '2004 (4)', '2005 (5)', '2006 (6)', '2007 (7)', '2008 (8)', '2009 (9)', '2010 (10)', '2011 (11)', '2012 (12)', '2013 (13)', '2014 (14)', '2015 (15)', '2016 (16)', 'All']

In [12]:
final_table1

,All employed (number of observations),Prefer to work less (%),Prefer to work more (%),All employed (number of observations),Prefer to work less (%),Prefer to work more (%)
2001 (1),4549.0,30.2,15.2,3976.0,26.7,17.2
2002 (2),4325.0,31.3,15.1,3763.0,24.6,17.6
2003 (3),4247.0,31.3,13.7,3744.0,25.2,17.4
2004 (4),4155.0,30.9,13.3,3667.0,25.9,16.3
2005 (5),4304.0,29.6,13.2,3943.0,26.2,16.9
2006 (6),4353.0,29.6,13.1,4004.0,26.1,15.3
2007 (7),4308.0,28.7,12.0,4034.0,26.6,15.3
2008 (8),4337.0,27.8,12.2,4032.0,25.2,14.5
2009 (9),4493.0,27.4,14.1,4084.0,23.8,15.8
2010 (10),4516.0,25.6,13.8,4149.0,24.5,16.8
2011 (11),5859.0,25.9,14.9,5375.0,24.0,17.3
2012 (12),5714.0,25.0,14.6,5291.0,23.6,16.6
2013 (13),5668.0,23.6,15.6,5275.0,23.4,16.5
2014 (14),5681.0,23.6,16.0,5295.0,22.8,18.5
2015 (15),5679.0,24.2,14.9,5361.0,22.9,17.2
2016 (16),5687.0,23.5,15.0,5357.0,22.4,17.2
All,77875.0,27.4,14.2,71350.0,24.6,16.7